#!/bin/sh
exe_path=$1
echo $exe_path
python3 pyinstxtractor.py $exe_path

exe_name=${exe_path##*/}
pyc_dir="./"$exe_name"_extracted/PYZ-00.pyz_extracted"
echo $pyc_dir

cd $pyc_dir
for f in `find . -name "*.pyc" -type f`;
do
    # f=$pyc_dir/$f
    echo $f # *.pyc
    l=${#f}
    echo ${f::$l-1} # *.py
    uncompyle6 $f > ${f::$l-1}
done