#!/bin/sh
work_path=$(dirname $0)
file='/usr/local/bin/quickopen'
# profile='~/.quickopen'
if [ ! -f "$file" ]; then
    ln -s $work_path/quickopen /usr/local/bin/quickopen
    echo "add quickopen script to environment path"
    # mkdir ~/.quickopen
    # mkdir ~/.quickopen/alias
    echo "create .quickopen file in User directoey"
else
    echo "quickopen exists in /usr/local/bin"
fi
exit
