#!/bin/sh
#functions
function help(){
    if [ $# == 0 ];then
    echo "help"
    elif [ $# == 1 ];then
    echo '$1'
    fi
}

function list(){

}

function new(){
}

function delete(){
listLenth=${#quickopenList}+1
quickopenList[$listLenth]='all'
# 循环遍历
fi

}

function version(){
    echo 'version: 1.0.0'
}
#variables
quickopenList=()
listLenth=0


# get quickopen list

listLenth=${#quickopenList}

# execute commands according to input
if [ $# == 0 ];then
    help
elif [ $# == 1 ];then
    if [ $1 == 'help' ];then
        help
    elif [ $1 == 'version' ];then
        version
    elif [ $1 == 'list' ];then
        list
    else
        echo 'no quickopen named $1'
    fi
elif [ $# == 2 ];then
    if [ $1 == 'del' ];then
        delete $2
    elif [ $1 == 'help' ];then
        help $2
    elif [ $1 == 'new' ];then
        new $2
    else

    fi
else
    echo "error command"
fi

exit
