#!/bin/sh
video_path=$1
len=0
for line in `cat timetable.txt`
do
    start_time=${line##*,}
    last_time=${line%,*}
    start_times[$len]=$start_time
    last_times[$len]=$last_time
    ((len+=1))
done

mkdir ./output
for ((i=0;i<$len;i++));
do
if [ $# -eq 1 ];then
    ffmpeg -t ${start_times[i]} -ss ${last_times[i]} -i $video_path -f gif -s 640x480 -r 10 ./output/$i.gif
    # -s 320x240 画幅 320x240 
    # -r 5 一秒帧数 5
elif [ $# -eq 2 ];then
    ffmpeg -t ${start_times[i]} -ss ${last_times[i]} -i $video_path $2 ./output/$i.gif
else
    echo error:too many paramas 
fi
done 
