#!/bin/sh
work_path=$(dirname $0)
file='/usr/local/bin/macrar'
if [ ! -f "$file" ]; then
    # echo $(cat $work_path/password.txt) |sudo -S 
    cp $work_path/password.txt /usr/local/bin/password.txt
    ln -s $work_path/macrar /usr/local/bin/macrar
else
    rm /usr/local/bin/macrar
fi
exit
