#!/bin/sh
video_path=$1


if [[ ! -d ./output ]];then
    mkdir ./output
fi   

ffmpeg -i $video_path -r 28 -s 1920x1080 -b 600k output/output.mp4
# -b 码率bps(bit per second)
# -r 帧率fps(frame per second)frame rate
# -s 分辨率