#!/bin/sh
work_path=$(dirname $0)
file='/usr/local/bin/ip'
if [ ! -f "$file" ]; then
    # echo $(cat $work_path/password.txt) |sudo -S 
    cp $work_path/password.txt /usr/local/bin/password.txt
    ln -s $work_path/ip /usr/local/bin/ip
    echo "add ip script to environment path"
else
    rm /usr/local/bin/ip
    echo "delete ip script"
fi
exit
